language: node_js
node_js:
  - node
branches:
  only:
    - master

stages:
  - test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - name: 'Linting'
      stage: test
      script: npm run lint
    - name: 'Unit Tests'
      stage: test
      script: npm run test
    - name: 'Native Build'
      stage: test
      script: npm run build && npx lerna run build:native
    - stage: deploy
      name: Deploy
      script: skip
      before_deploy: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx multi-semantic-release

cache: npm
