language: node_js
node_js:
  - node
branches:
  only:
    - master
    - develop

stages:
  - build
  - test
  - name: deploy
    if: branch = master AND type != pull_request

jobs:
  include:
    - &Build
      name: 'Latest: Building'
      stage: build
      script: npm run build
      node_js: node
    - <<: *Build
      name: '10: Building'
      node_js: '10'
    - name: 'Linting'
      stage: test
      script: npm run lint
    - &Test
      name: 'Latest: Unit Tests'
      stage: test
      script: npm run test
      node_js: node
    - <<: *Test
      name: '10: Unit Tests'
      node_js: '10'
    - stage: deploy
      node_js: lts/*
      name: Deploy
      script: npm run build
      after_success:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" > /dev/null 2>&1
        - git checkout master
      deploy:
        provider: script
        skip_cleanup: true
        script: npx lerna publish

cache: npm
